server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: padmajad
  application:
    name: HOTEL-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    #fetchRegistry: false
    #registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
