## Spring data source
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: padmajad
##Include Swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: USER-SERVICE
##Hibernate
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081

eureka:
  client:
    #fetchRegistry: false
    #registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost



