spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices
      host: localhost
      port: 27017
  application:
    name: RATING-SERVICE
server:
  port: 8083
debug: true
eureka:
  client:
    #fetchRegistry: false
    #registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

